version: '3'
services:
    # App
    app:
        command: >
            bash -c "php -d xdebug.mode=coverage vendor/bin/phpunit --fail-on-warning --fail-on-risky"
        build:
            args:
                BUILD_DEPENDENCIES: 1
                APP_ENV: test
