parameters:

services:
    ZFekete\SweefyBundle\Service\RSOMetaDataBuilder:
        public: false

    sweefy.service.rso_meta_data_builder:
        class: ZFekete\SweefyBundle\Service\RSOMetaDataBuilder
        public: true


    ZFekete\SweefyBundle\Service\ObjectHydrator:
        public: false
        arguments:
            - '@ZFekete\SweefyBundle\Service\RSOMetaDataBuilder'

    sweefy.service.object_hydrator:
        class: '@ZFekete\SweefyBundle\Service\ObjectHydrator'
        public: true

    ZFekete\SweefyBundle\Contract\ObjectHydratorInterface: '@ZFekete\SweefyBundle\Service\ObjectHydrator'


    ZFekete\SweefyBundle\Service\ResultHydrator:
        autowire: true
        public: false

    sweefy.service.result_hydrator:
        class: ZFekete\SweefyBundle\Service\ResultHydrator
        public: true

    ZFekete\SweefyBundle\Contract\ResultHydratorInterface: '@ZFekete\SweefyBundle\Service\ResultHydrator'


    ZFekete\SweefyBundle\Service\Sweefy:
        autowire: true
        public: false

    sweefy.service.sweefy:
        class: ZFekete\SweefyBundle\Service\Sweefy
        public: true

