name: Checks for PRs

on: pull_request

jobs:
    test:
        name: Tests
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                php-version: [ '8.1' ]

        steps:
        -   name: Checkout
            uses: actions/checkout@v2

        -   name: Run tests
            env:
                PHP_VERSION: ${{ matrix.php-version }}
            run: make test
